(()=>{
'use strict';
const API_URL='https://backend-ingles-e3ms.onrender.com';
const SUPABASE_URL='https://lqdgbmuodnshfgokesvd.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_ivnebDTQZ9SeyZQUHBKtmg_yRtH6mFu';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let recoveryMode=false;
sb.auth.onAuthStateChange((_event,session)=>{if(_event==='PASSWORD_RECOVERY'){recoveryMode=true;closeAuth();$('reset-modal').style.display='flex';return}if(!recoveryMode)syncUser(session?.user||null)});
const $=id=>document.getElementById(id);const $$=sel=>Array.from(document.querySelectorAll(sel));
const state={user:null,subscribed:false,authRegister:false,pron:'lectura',recording:false,recorder:null,chunks:[],timer:null,seconds:0,dictation:'',reading:null,callMessages:[],callRecorder:null,callChunks:[],callBusy:false};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){const t=$('toast');t.textContent=msg;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',3200)}
let mascotRevertTimer=null;
let mascotBlinkTimer=null;
const MASCOT_PEEK_IMG="assets/img-039fa38f.webp";
const EYE_OPEN_L="assets/img-2aa8b477.webp";
const EYE_OPEN_R="assets/img-f298199c.webp";
const EYE_CLOSED_L="assets/img-5f908050.webp";
const EYE_CLOSED_R="assets/img-a0344521.webp";
let mascotClickTimes=[];
function eyesClosed(closed){const l=$('mascot-eye-l'),r=$('mascot-eye-r');if(!l||!r)return;const li=l.querySelector('img'),ri=r.querySelector('img');li.src=closed?EYE_CLOSED_L:EYE_OPEN_L;ri.src=closed?EYE_CLOSED_R:EYE_OPEN_R}
function scheduleBlink(){clearTimeout(mascotBlinkTimer);const wait=2600+Math.random()*3200;mascotBlinkTimer=setTimeout(()=>{const el=$('mascot');if(el&&!el.className.includes('state-pensando')){eyesClosed(true);setTimeout(()=>eyesClosed(false),160)}scheduleBlink()},wait)}
function setMascotState(state,autoRevertMs){const el=$('mascot');if(!el)return;el.className='mascot-widget state-'+state;eyesClosed(state==='pensando');clearTimeout(mascotRevertTimer);if(autoRevertMs)mascotRevertTimer=setTimeout(()=>setMascotState('idle'),autoRevertMs)}
function spawnConfetti(){const colors=['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#f472b6'];const host=$('mascot');for(let i=0;i<14;i++){const c=document.createElement('div');c.className='confetti-piece';c.style.background=colors[i%colors.length];c.style.left=(38+Math.random()*24)+'%';c.style.setProperty('--dx',(Math.random()*90-45)+'px');c.style.setProperty('--dy',(-(60+Math.random()*50))+'px');c.style.animationDelay=(Math.random()*0.12)+'s';host.appendChild(c);setTimeout(()=>c.remove(),1100)}}
function spawnEggSequence(){const egg=$('mascot-egg');clearTimeout(egg._t1);clearTimeout(egg._t2);egg.textContent='🥚';egg.classList.remove('hatch');egg.classList.add('show');egg._t1=setTimeout(()=>{egg.textContent='🐣';egg.classList.add('hatch');spawnConfetti()},850);egg._t2=setTimeout(()=>{egg.classList.remove('show','hatch')},2700)}
function reactToScore(score){const n=Number(score)||0;if(n>=70){setMascotState('feliz',3200);spawnEggSequence()}else{setMascotState('triste',4500)}}
function startMascotTalking(){$('mascot-mouth').classList.add('talk')}
function stopMascotTalking(){$('mascot-mouth').classList.remove('talk')}
function showCardPeek(){const activeSection=document.querySelector('.section.active');if(!activeSection)return;const card=activeSection.querySelector('.card');if(!card)return;card.style.position=card.style.position||'relative';let peek=document.getElementById('mascot-peek');if(!peek){peek=document.createElement('img');peek.id='mascot-peek';peek.className='mascot-peek';peek.src=MASCOT_PEEK_IMG;peek.alt=''}card.appendChild(peek);requestAnimationFrame(()=>peek.classList.add('show'));clearTimeout(window._peekTimer);window._peekTimer=setTimeout(()=>peek.classList.remove('show'),3500)}
function mascotClicked(){const now=Date.now();mascotClickTimes=mascotClickTimes.filter(t=>now-t<2200);mascotClickTimes.push(now);if(mascotClickTimes.length>=5){mascotClickTimes=[];setMascotState('feliz',3200);spawnEggSequence()}}
scheduleBlink();
function busy(id,on,label){const b=$(id);if(!b)return;if(on){if(!b.dataset.original)b.dataset.original=b.textContent;b.textContent=label;b.disabled=true;b.classList.add('loading');setMascotState('pensando')}else{b.disabled=false;b.textContent=b.dataset.original||label;b.classList.remove('loading');setMascotState('idle');if(Math.random()<0.5)setTimeout(showCardPeek,400)}}
function showAuth(){ $('auth-error').style.display='none'; $('auth-modal').style.display='flex'; setTimeout(()=>$('auth-email').focus(),50)}
function closeAuth(){ $('auth-modal').style.display='none' }
function authError(msg){$('auth-error').textContent=msg||'';$('auth-error').style.display=msg?'block':'none'}
function resetError(msg){$('reset-error').textContent=msg||'';$('reset-error').style.display=msg?'block':'none'}
async function forgotPassword(){const email=$('auth-email').value.trim();if(!email)return authError('Escribe tu correo arriba primero, luego dale a "¿Olvidaste tu contraseña?".');busy('auth-forgot',true,'Enviando...');authError('');try{const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(r.error)throw r.error;toast('Te enviamos un correo para restablecer tu contraseña. Revisa spam si no lo ves.')}catch(e){authError(e.message||'No se pudo enviar el correo.')}finally{busy('auth-forgot',false,'¿Olvidaste tu contraseña?')}}
async function resetSubmit(){const pw=$('reset-password').value;if(!pw||pw.length<6)return resetError('La contraseña debe tener al menos 6 caracteres.');busy('reset-submit',true,'Guardando...');resetError('');try{const r=await sb.auth.updateUser({password:pw});if(r.error)throw r.error;$('reset-modal').style.display='none';toast('Contraseña actualizada. Ya puedes usar tu cuenta.');await syncUser(r.data.user)}catch(e){resetError(e.message||'No se pudo guardar la contraseña.')}finally{busy('reset-submit',false,'Guardar nueva contraseña')}}
async function getSession(){const r=await sb.auth.getSession();if(r.error)throw r.error;return r.data.session||null}
async function authFetch(path,options={}){let s=await getSession();if(!s){showAuth();throw new Error('Please sign in to continue.')}const headers=new Headers(options.headers||{});headers.set('Authorization','Bearer '+s.access_token);const wakeT=setTimeout(()=>{if(!state.wakeShown){state.wakeShown=true;toast('Waking up the server… this can take up to a minute the first time.')}},5000);let r;try{r=await fetch(API_URL+path,{...options,headers})}finally{clearTimeout(wakeT)}if(r.status===401){const refreshed=await sb.auth.refreshSession();if(refreshed.data.session){headers.set('Authorization','Bearer '+refreshed.data.session.access_token);r=await fetch(API_URL+path,{...options,headers})}}return r}
async function jsonFetch(path,options={}){const r=await authFetch(path,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('Request failed ('+r.status+')'));return d}
async function syncUser(user){state.user=user;const content=$('app-content'),locked=$('locked-view');if(!user){document.querySelector('.app').style.display='none';$('welcome-view').style.display='flex';closeAuth();return}document.querySelector('.app').style.display='';$('welcome-view').style.display='none';$('user-display').textContent=user.email||'Signed in';$('side-email').textContent=user.email||'Student';$('login-btn').style.display='none';$('logout-btn').style.display='inline-block';try{const d=await jsonFetch('/api/session');if(!d.authenticated)throw new Error('The session is not recognized by the server.');state.subscribed=!!d.is_subscribed;renderAccountInfo(user,d);applyProfileIdentity(user,d);if(d.es_admin){$('nav-admin').style.display='inline-block'}if(d.en_prueba){$('side-status').textContent=`Free trial · ${d.trial_dias_restantes} day(s) left`}else{$('side-status').textContent=state.subscribed?'Practice access active':'Trial ended · subscribe to continue'}content.style.display=state.subscribed?'block':'none';locked.style.display=state.subscribed?'none':'block';if(state.subscribed){if(d.user&&!d.user.onboarded){content.style.display='none';initOnboarding()}else{closeAuth();loadDashboard();loadReading().catch(()=>{});loadDictation().catch(()=>{});}}}catch(e){console.error('[SESSION]',e);state.subscribed=false;content.style.display='none';locked.style.display='block';$('side-status').textContent='Access check failed';toast('We could not verify your access. Please sign in again.')}}
function section(name,button){if(!state.user||!state.subscribed){showAuth();return}$$('.section').forEach(s=>s.classList.toggle('active',s.id==='sec-'+name));$$('#main-nav button,[data-section-jump]').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active');const nav=document.querySelector(`#main-nav button[data-section="${name}"]`);if(nav)nav.classList.add('active');if(name==='escritura')loadWritingChallenge();if(name==='lectura')loadReadingLibrary().catch(e=>toast(e.message));if(name==='escucha')loadListeningLibrary().catch(e=>toast(e.message));if(name==='historial')loadProgress().catch(e=>toast(e.message));if(name==='admin')loadAdminActivity();if(name==='home')loadDashboard();if(name==='logros')loadAchievements();if(name==='shop')loadShop();if(name==='notificaciones')loadNotifications();if(name==='vocabulario'){loadVocabDaily();refreshSrs()}if(name!=='llamada')vadStop();if(name==='learning-path')loadLearningPath();setTimeout(showCardPeek,600)}
let writingLevel='intermediate';
const WRITING_TARGETS={easy:80,intermediate:150,advanced:220};
async function loadWritingChallenge(){$('writing-challenge-card').style.display='block';$('writing-challenge-text').textContent='Loading a challenge for you...';try{const d=await jsonFetch('/api/writing/challenge?nivel='+writingLevel);$('writing-challenge-text').textContent=d.prompt||'';updateWritingWordcount()}catch(e){$('writing-challenge-text').textContent='Could not load a challenge — write about anything you like.'}}
function setWritingLevel(level,btn){writingLevel=level;$$('#writing-level-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.level===level));loadWritingChallenge()}
function updateWritingWordcount(){const n=$('writing').value.trim().split(/\s+/).filter(Boolean).length;const showTarget=$('writing-challenge-card').style.display!=='none';$('writing-wordcount').textContent=showTarget?`${n}/${WRITING_TARGETS[writingLevel]} words`:n+(n===1?' word':' words')}
async function loadShop(){$('shop-units').innerHTML='<div class="empty">Loading...</div>';$('shop-frames').innerHTML='';try{const d=await jsonFetch('/api/shop');$('shop-gems').textContent=`💎 ${d.gems} gems`;$('shop-freezes').textContent=`🧊 ${d.streak_freezes} streak freeze${d.streak_freezes===1?'':'s'}`;$('shop-buy-freeze').textContent=`Buy — ${d.streak_freeze_price} 💎`;$('shop-units').innerHTML=(d.unit_offers||[]).map(u=>`<div class="card" style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:10px"><div><b style="font-size:14px">${esc(u.title)}</b></div><button type="button" class="btn" data-unlock-unit="${u.unit_code}">Unlock — ${u.price} 💎</button></div>`).join('')||'<div class="empty">No units available to unlock right now.</div>';$$('#shop-units [data-unlock-unit]').forEach(b=>b.addEventListener('click',()=>buyItem('unlock_unit:'+b.dataset.unlockUnit)));$('shop-frames').innerHTML=(d.frames||[]).map(f=>`<div class="report" style="text-align:center"><div style="width:52px;height:52px;border-radius:50%;margin:0 auto 8px;background:${f.gradient}"></div><b style="display:block;font-size:13px">${esc(f.name)}</b><button type="button" class="btn${f.id===d.avatar_frame?' primary':''}" style="margin-top:8px;width:100%" data-frame="${f.id}">${f.owned?(f.id===d.avatar_frame?'Equipped':'Equip'):('Buy — '+f.price+' 💎')}</button></div>`).join('');$$('#shop-frames [data-frame]').forEach(b=>b.addEventListener('click',()=>buyItem('frame:'+b.dataset.frame)))}catch(e){$('shop-units').innerHTML='<div class="empty">Could not load the shop.</div>';toast(e.message)}}
async function buyItem(item){try{await jsonFetch('/api/shop/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item})});toast('Done!');await loadShop();const s=await jsonFetch('/api/session');applyProfileIdentity(state.user,s)}catch(e){toast(e.message)}}
async function loadNotifications(){$('notif-list').innerHTML='<div class="empty">Loading...</div>';try{const [dash,ach]=await Promise.all([jsonFetch('/api/dashboard'),jsonFetch('/api/achievements')]);const cards=[];
if(dash.streak_days>0)cards.push({icon:'🔥',text:`You're on a ${dash.streak_days}-day streak! Keep it going today.`});
if(dash.daily_goal_pct>=100)cards.push({icon:'✅',text:'You\'ve completed today\'s goal. Great job!'});
else if(dash.daily_goal_pct>0)cards.push({icon:'🎯',text:`Today's goal is at ${dash.daily_goal_pct}% — a bit more and you're done.`});
else cards.push({icon:'🎯',text:'You haven\'t started today\'s goal yet — even a few minutes counts.'});
(ach.achievements||[]).filter(a=>!a.unlocked&&a.progress>=50).slice(0,3).forEach(a=>cards.push({icon:'🏅',text:`Almost there: ${a.title} is ${a.progress}% complete.`}));
(ach.achievements||[]).filter(a=>a.unlocked).slice(-2).forEach(a=>cards.push({icon:a.icon||'🏆',text:`Unlocked: ${a.title}`}));
$('notif-list').innerHTML=cards.length?cards.map(c=>`<div class="card" style="display:flex;gap:12px;align-items:center;margin-bottom:10px"><div style="font-size:22px">${c.icon}</div><div style="font-size:13px">${esc(c.text)}</div></div>`).join(''):'<div class="empty">You\'re all caught up — nothing new right now.</div>'
}catch(e){$('notif-list').innerHTML='<div class="empty">Could not load notifications.</div>';toast(e.message)}}
function pronMode(mode){state.pron=mode;$$('.mode[data-pron]').forEach(b=>b.classList.toggle('active',b.dataset.pron===mode));['lectura','habla_libre','trabalenguas'].forEach(x=>{const el=$('panel-'+x);if(el)el.classList.toggle('active',x===mode)});if(mode==='tutor'){section('tutor');return}$('pron-result').style.display='none'}
let settingsAutoplay=localStorage.getItem('talvo_autoplay')!=='off';
let settingsSpeechRate=localStorage.getItem('talvo_speech_rate')||'normal';
function applySettingsUI(){$$('#setting-autoplay-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.val===(settingsAutoplay?'on':'off')));$$('#setting-rate-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.val===settingsSpeechRate))}
function setSettingAutoplay(val){settingsAutoplay=val==='on';localStorage.setItem('talvo_autoplay',val);applySettingsUI()}
function setSettingRate(val){settingsSpeechRate=val;localStorage.setItem('talvo_speech_rate',val);applySettingsUI()}
function speak(text,rate=1){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||''));u.lang='en-US';u.rate=rate*(settingsSpeechRate==='slow'?0.75:1);speechSynthesis.speak(u)}
async function playGuideAudio(text,btnId){if(!text)return toast('Genera una frase primero.');busy(btnId,true,'Cargando...');try{const r=await authFetch('/api/sintetizar-audio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto:text})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'No se pudo generar el audio.')}const blob=await r.blob();const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.play();audio.onended=()=>URL.revokeObjectURL(url)}catch(e){toast(e.message)}finally{busy(btnId,false,'🔊 Escuchar')}}
async function newPhrase(){busy('new-phrase',true,'Generating...');try{const d=await jsonFetch('/nueva-frase');$('phrase').textContent=d.frase||'';$('translation').textContent=d.traduccion||''}catch(e){toast(e.message)}finally{busy('new-phrase',false,'New sentence')}}
function customPhrase(){const v=$('custom-phrase').value.trim();if(!v)return toast('Write a sentence first.');$('phrase').textContent=v;$('translation').textContent='Custom sentence';$('custom-phrase').value='';$('pron-result').style.display='none'}
async function newTopic(){busy('new-topic',true,'Generating...');try{const d=await jsonFetch('/nuevo-tema-libre');$('free-topic').textContent=d.tema||'';$('free-instructions').textContent=d.instrucciones||''}catch(e){toast(e.message)}finally{busy('new-topic',false,'New topic')}}
async function newTwister(){busy('new-twister',true,'Generating...');try{const d=await jsonFetch('/nuevo-trabalenguas');$('twister').textContent=d.trabalenguas||'';$('twister-focus').textContent='Focus: '+(d.enfoque||'')}catch(e){toast(e.message)}finally{busy('new-twister',false,'New challenge')}}
function resetTimer(){clearInterval(state.timer);state.timer=null;state.seconds=0}
function startTimer(){resetTimer();state.timer=setInterval(()=>{state.seconds++;$('record-btn').textContent=`Recording... ${state.seconds}s · Click to stop`},1000)}
let waveformCtx=null,waveformRAF=null,waveformAnalyser=null;
function startWaveform(stream){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;waveformCtx=new AudioCtx();const source=waveformCtx.createMediaStreamSource(stream);waveformAnalyser=waveformCtx.createAnalyser();waveformAnalyser.fftSize=256;source.connect(waveformAnalyser);const canvas=$('pron-waveform');if(!canvas)return;const ctx2d=canvas.getContext('2d');const bufferLength=waveformAnalyser.frequencyBinCount;const dataArray=new Uint8Array(bufferLength);const draw=()=>{waveformRAF=requestAnimationFrame(draw);waveformAnalyser.getByteFrequencyData(dataArray);ctx2d.clearRect(0,0,canvas.width,canvas.height);const barWidth=canvas.width/bufferLength*2.2;let x=0;for(let i=0;i<bufferLength;i++){const v=dataArray[i]/255;const barHeight=v*canvas.height;ctx2d.fillStyle='rgba('+(getComputedStyle(document.documentElement).getPropertyValue('--c1-rgb').trim()||'62,232,255')+','+(0.4+v*0.6)+')';ctx2d.fillRect(x,canvas.height-barHeight,barWidth-2,barHeight);x+=barWidth;if(x>canvas.width)break}};draw()}catch(e){}}
function stopWaveform(){if(waveformRAF)cancelAnimationFrame(waveformRAF);waveformRAF=null;if(waveformCtx){try{waveformCtx.close()}catch(e){}waveformCtx=null}const canvas=$('pron-waveform');if(canvas){const ctx2d=canvas.getContext('2d');ctx2d.clearRect(0,0,canvas.width,canvas.height)}}
async function toggleRecording(){const b=$('record-btn');if(state.recording){resetTimer();state.recording=false;b.classList.remove('recording');b.textContent='Analyzing...';stopWaveform();try{state.recorder.stop();state.recorder.stream?.getTracks().forEach(t=>t.stop())}catch(e){toast('Recording could not be stopped.')}}else{if(!navigator.mediaDevices?.getUserMedia)return toast('Your browser does not support microphone recording.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});let mime='audio/webm';if(window.MediaRecorder&&MediaRecorder.isTypeSupported){if(!MediaRecorder.isTypeSupported(mime)){const alternatives=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];mime=alternatives.find(x=>MediaRecorder.isTypeSupported(x))||''}}state.chunks=[];state.recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.recorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.recorder.onstop=sendRecording;state.recorder.start();state.recording=true;b.classList.add('recording');b.textContent='Recording... 0s · Click to stop';startTimer();startWaveform(stream)}catch(e){toast('Microphone error: '+e.message)}}}
const COACH_TIPS={"Phonetic accuracy":"Focus on individual sounds — try saying tricky words slowly, then at natural speed.","Pronunciation":"Focus on individual sounds — try saying tricky words slowly, then at natural speed.","Fluency":"Practice speaking in longer phrases without stopping. Reading a passage aloud a few times really helps.","Completeness":"Make sure to say every word in the sentence — avoid skipping or rushing through parts.","Prosody":"Work on your intonation — exaggerate the natural rise and fall of the sentence as you practice.","Grammar":"Review the grammar patterns you used, and try rewriting the sentence with correct verb tenses.","Vocabulary":"Try using more specific or varied words — Today's Vocabulary has new words daily.","Coherence":"Organize your ideas with clear connectors like \"first\", \"then\", \"because\".","English quality":"Review your word choice and sentence structure for a more natural flow.","Accuracy":"Reread carefully and double-check the details before answering.","Listening accuracy":"Play it again and focus on one phrase at a time — pausing between words is totally fine while you practice."};
function renderCoachInsight(containerId,metrics,actions){const valid=metrics.filter(m=>m.value!=null&&!isNaN(Number(m.value)));if(!valid.length){$(containerId).innerHTML='';return}const weakest=valid.reduce((a,b)=>Number(b.value)<Number(a.value)?b:a);const tip=COACH_TIPS[weakest.label]||'Keep practicing consistently — small daily sessions add up fast.';const acts=actions||[];const btnsHtml=acts.map((a,i)=>`<button type="button" class="btn${i===0?' primary':''}" id="${containerId}-action-${i}" style="margin:4px 8px 0 0">${esc(a.label)}</button>`).join('');$(containerId).innerHTML=`<div class="card" style="margin-top:14px;background:linear-gradient(135deg,rgba(113,128,255,.14),rgba(113,128,255,.02))"><div style="font-size:11px;color:var(--primary);font-weight:700;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">🧭 Coach insight</div><p style="font-size:13px;margin:0 0 ${acts.length?'2px':'0'}">To sound more fluent, work on your <b>${esc(weakest.label.toLowerCase())}</b> score (${Math.round(weakest.value)}%). ${esc(tip)}</p>${btnsHtml}</div>`;acts.forEach((a,i)=>$(`${containerId}-action-${i}`)?.addEventListener('click',a.fn))}
async function goToLearningPathFor(tool){try{$$('.section').forEach(s=>s.classList.toggle('active',s.id==='sec-learning-path'));$$('#main-nav button,[data-section-jump]').forEach(b=>b.classList.remove('active'));const navBtn=$('main-nav')?.querySelector('button[data-section="learning-path"]');if(navBtn)navBtn.classList.add('active');closeSidebar();const d=await jsonFetch('/api/learning-path');lpState.units=d.units;const unit=(d.units||[]).find(u=>u.unlocked&&!u.completed)||(d.units||[])[0];if(!unit)return toast('No learning path units available yet.');await openLearningUnit(unit.code);const topic=(lpState.topics||[]).find(t=>!t.completed)||(lpState.topics||[])[0];if(topic){openLearningTopic(topic.id);startLearningPractice(tool)}}catch(e){toast(e.message)}}
function renderPaceGauge(containerId,wpm){if(!wpm){$(containerId).innerHTML='';return}const min=60,max=220;const pct=Math.max(0,Math.min(1,(wpm-min)/(max-min)));const angle=180*pct;const cx=100,cy=100,r=80;const rad=(180-angle)*Math.PI/180;const nx=cx+r*0.78*Math.cos(rad),ny=cy-r*0.78*Math.sin(rad);const label=wpm<100?'Slow':wpm<170?'Good pace':'Fast';const color=wpm<100?'#f5a524':wpm<170?'#22c55e':'#f5a524';const circ=Math.PI*r;$(containerId).innerHTML=`<label class="field-label">Speaking rate</label><svg viewBox="0 0 200 110" style="width:100%;max-width:200px;display:block;margin:0 auto"><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="var(--line)" stroke-width="10" stroke-linecap="round"/><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="${color}" stroke-width="10" stroke-linecap="round" stroke-dasharray="${angle/180*circ} ${circ}"/><line x1="${cx}" y1="${cy}" x2="${nx}" y2="${ny}" stroke="var(--text)" stroke-width="3" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="5" fill="var(--text)"/></svg><div style="text-align:center;margin-top:-4px"><b style="font-size:18px">${wpm}</b> <small style="color:var(--muted)">wpm</small> · <small style="color:${color};font-weight:700">${label}</small></div>`}
function radarPoints(n,radius,cx,cy,scale){const pts=[];for(let i=0;i<n;i++){const angle=(-90+i*(360/n))*Math.PI/180;pts.push([cx+radius*scale*Math.cos(angle),cy+radius*scale*Math.sin(angle)])}return pts}
function renderRadar(containerId,items){const n=items.length;if(n<3){$(containerId).innerHTML='';return}const cx=100,cy=100,R=72;const gid='radarGrad'+Math.random().toString(36).slice(2,8);let svg=`<svg viewBox="0 0 200 200" style="width:100%;max-width:230px;display:block;margin:0 auto"><defs><radialGradient id="${gid}" cx="50%" cy="50%" r="65%"><stop offset="0%" stop-color="var(--primary)" stop-opacity=".5"/><stop offset="100%" stop-color="var(--primary2)" stop-opacity=".1"/></radialGradient></defs>`;[0.25,0.5,0.75,1].forEach(lv=>{const pts=radarPoints(n,R,cx,cy,lv);svg+=`<polygon points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="var(--line)" stroke-width="1"/>`});const axisPts=radarPoints(n,R,cx,cy,1);axisPts.forEach(p=>{svg+=`<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}" stroke="var(--line)" stroke-width="1"/>`});const valPts=items.map((it,i)=>{const v=Math.max(0,Math.min(100,Number(it.value)||0))/100;return radarPoints(n,R,cx,cy,v)[i]});svg+=`<polygon class="radar-fill" points="${valPts.map(p=>p.join(',')).join(' ')}" fill="url(#${gid})" stroke="var(--primary)" stroke-width="2" style="transform-origin:${cx}px ${cy}px;transform:scale(0);transition:transform .6s cubic-bezier(.34,1.56,.64,1)"/>`;valPts.forEach(p=>{svg+=`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="var(--primary)"/>`});axisPts.forEach((p,i)=>{const lx=cx+(p[0]-cx)*1.32,ly=cy+(p[1]-cy)*1.32;svg+=`<text x="${lx}" y="${ly}" text-anchor="middle" dominant-baseline="middle" font-size="9" fill="var(--muted)">${esc(items[i].label)}</text>`});svg+='</svg>';$(containerId).innerHTML=svg;requestAnimationFrame(()=>requestAnimationFrame(()=>{const el=$(containerId).querySelector('.radar-fill');if(el)el.style.transform='scale(1)'}))}
function renderMetrics(items){$('metric-list').innerHTML=items.map(x=>{const v=Math.max(0,Math.min(100,Number(x.value)||0));return `<div><div class="metric-head"><span>${esc(x.label)}</span><span>${Math.round(v)}%</span></div><div class="bar"><div class="fill" style="width:${v}%"></div></div></div>`}).join('')}
const MOUTH_TIPS={omisiones:{icon:'👄',title:"You're skipping some sounds",tip:"Make sure to pronounce word endings fully, especially -s, -ed and -ing. Try exaggerating the last sound of each word as you practice."},pronunciaciones_incoherentes:{icon:'🗣️',title:'Some sounds need sharpening',tip:"Slow down on the tricky word and isolate the sound — say just that word three times before the full sentence."},inserciones:{icon:'🚫',title:'Extra sounds are sneaking in',tip:"Avoid adding a vowel sound between consonants — try saying the consonant cluster softly, without a pause between letters."},interrupcion_inesperada:{icon:'💨',title:'Unexpected pauses',tip:"Take a breath before you start speaking so you don't run out of air mid-sentence."},falta_un_descanso:{icon:'⏸️',title:'Missing natural pauses',tip:"Pause briefly at commas and periods — it makes your speech sound more natural and gives you time to breathe."},monotona:{icon:'🎵',title:'Try more intonation',tip:"English rises and falls a lot. Exaggerate the pitch on the most important word in the sentence — it will feel strange at first, but that's how natural English sounds."}};
function renderMouthTips(containerId,insp){const active=Object.entries(insp||{}).filter(([k,v])=>v>0&&MOUTH_TIPS[k]);if(!active.length){$(containerId).innerHTML='';return}$(containerId).innerHTML='<label class="field-label">How to improve</label>'+active.map(([k])=>{const t=MOUTH_TIPS[k];return `<div class="card" style="margin-top:8px;padding:12px"><div style="display:flex;gap:10px;align-items:flex-start"><div style="font-size:20px">${t.icon}</div><div><b style="font-size:13px;display:block;margin-bottom:3px">${esc(t.title)}</b><small style="color:var(--muted)">${esc(t.tip)}</small></div></div></div>`}).join('')}
function renderPron(d){const insp=d.inspeccion||{};renderMouthTips('pron-mouth-tips',insp);$('i-omission').textContent=insp.omisiones||0;$('i-mispron').textContent=insp.pronunciaciones_incoherentes||insp.incoherentes||0;$('i-insertion').textContent=insp.inserciones||0;$('i-break').textContent=insp.interrupcion_inesperada||0;$('i-missing').textContent=insp.falta_un_descanso||0;$('i-monotone').textContent=insp.monotona||0;
const strengthMap=[[insp.omisiones,'Complete words'],[insp.pronunciaciones_incoherentes||insp.incoherentes,'Consistent sounds'],[insp.inserciones,'No extra sounds'],[insp.interrupcion_inesperada,'Smooth flow'],[insp.falta_un_descanso,'Natural pauses'],[insp.monotona,'Good intonation']];
const strengths=strengthMap.filter(([count])=>!count).map(([,label])=>label).slice(0,4);
$('pron-strengths').innerHTML=strengths.length?strengths.map(s=>`<span class="badge" style="font-size:11px;padding:6px 10px">✓ ${esc(s)}</span>`).join(''):'';$('global-score').textContent=Math.round(Number(d.puntuacion_global||0));const gscore=Number(d.puntuacion_global||0);$('global-score').className='circle '+(gscore>=80?'good':gscore>=60?'mid':'low');if(state.pron==='habla_libre'&&d.content_assessment){const c=d.content_assessment;const m=[{label:'Pronunciation',value:d.precision},{label:'Fluency',value:d.fluidez},{label:'Grammar',value:d.gramatica||c.grammar_score},{label:'Vocabulary',value:d.vocabulario||c.vocabulary_score}];renderMetrics(m);renderRadar('pron-radar',m);renderCoachInsight('pron-coach',m,[{label:'📍 Practice in Learning Path',fn:()=>goToLearningPathFor('pronunciation')}])}else{const m=[{label:'Phonetic accuracy',value:d.precision},{label:'Fluency',value:d.fluidez},{label:'Completeness',value:d.completitud},{label:'Prosody',value:d.prosodia}];renderMetrics(m);renderRadar('pron-radar',m);renderCoachInsight('pron-coach',m,[{label:'📍 Practice in Learning Path',fn:()=>goToLearningPathFor('pronunciation')}])}$('pron-recording').innerHTML=state.lastRecordingUrl?`<label class="field-label">Your recording</label><audio controls src="${state.lastRecordingUrl}" style="width:100%"></audio>`:'';renderPaceGauge('pron-pace',d.velocidad_wpm);$('words').innerHTML='';(d.palabras||[]).forEach(item=>{const score=Number(item.precision??item.puntuacion??0);const b=document.createElement('button');b.type='button';b.className='word '+(score>=80?'good':score>=60?'mid':'low');b.innerHTML=`<b>${esc(item.palabra)}</b><small>${Math.round(score)}%</small>`;b.addEventListener('click',()=>showPhonemes(item));$('words').appendChild(b)});$('phonemes').style.display='none';$('pron-result').style.display='block';$('pron-result').scrollIntoView({behavior:'smooth',block:'nearest'});reactToScore(d.puntuacion_global);renderPronTrend()}
function showPhonemes(item){state.phWord=item.palabra||'';$('phonemes').style.display='block';$('phoneme-title').textContent=`${item.palabra||'Word'} · ${item.precision??item.puntuacion??0}%`;$('chips').innerHTML=(item.fonemas||[]).map(p=>`<span class="chip">/${esc(p.fonema)}/ · ${p.precision??0}%</span>`).join('')||'<span style="color:var(--muted);font-size:11px">No phoneme detail available.</span>'}
async function sendRecording(){const blob=new Blob(state.chunks,{type:state.chunks[0]?.type||'audio/webm'});if(state.lastRecordingUrl)URL.revokeObjectURL(state.lastRecordingUrl);state.lastRecordingUrl=URL.createObjectURL(blob);const fd=new FormData();fd.append('audio',blob,'recording.webm');let path='/analizar-audio-real';if(state.pron==='lectura'){fd.append('frase_esperada',$('phrase').textContent.trim());fd.append('modo','lectura')}else if(state.pron==='trabalenguas'){fd.append('frase_esperada',$('twister').textContent.trim());fd.append('modo','trabalenguas')}else{path='/api/assess-unscripted';fd.append('topic',$('free-topic').textContent.trim());fd.append('modo','habla_libre')}try{const d=await jsonFetch(path,{method:'POST',body:fd});renderPron(d)}catch(e){toast(e.message)}finally{$('record-btn').textContent='Start recording';$('record-btn').classList.remove('recording');state.chunks=[]}}
async function analyzeWriting(){const text=$('writing').value.trim();if(!text)return toast('Write something first.');busy('writing-submit',true,'Analyzing...');try{const d=await jsonFetch('/analizar-escritura',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto:text})});$('w-score').textContent=Math.round(d.puntuacion||0);$('w-grammar').textContent=Math.round(d.gramatica||0);$('w-vocab').textContent=Math.round(d.vocabulario||0);$('w-coherence').textContent=Math.round(d.coherencia||0);$('w-summary').textContent=d.resumen||'';$('w-corrections').innerHTML=(d.correcciones||[]).map(x=>`<li>${esc(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')||'<li>No corrections.</li>';$('w-better').textContent=d.version_mejorada||'';$('writing-result').style.display='block';reactToScore(d.puntuacion);renderCoachInsight('writing-coach',[{label:'Grammar',value:d.gramatica},{label:'Vocabulary',value:d.vocabulario},{label:'Coherence',value:d.coherencia}],[{label:'🔄 Try a new challenge',fn:loadWritingChallenge},{label:'📍 Practice in Learning Path',fn:()=>goToLearningPathFor('writing')}])}catch(e){toast(e.message)}finally{busy('writing-submit',false,'Analyze writing')}}
let readingLibraryItems=[];
let readingLibraryFilter='all';
async function loadReadingLibrary(){$('reading-library-view').style.display='block';$('reading-practice-view').style.display='none';$('reading-library-list').innerHTML='<div class="empty">Loading...</div>';try{const d=await jsonFetch('/api/reading/library');readingLibraryItems=d.items||[];renderReadingLibraryList()}catch(e){$('reading-library-list').innerHTML='<div class="empty">Could not load the library.</div>';toast(e.message)}}
function renderReadingLibraryList(){const items=readingLibraryItems.filter(x=>readingLibraryFilter==='all'||x.level===readingLibraryFilter);$('reading-library-list').innerHTML=items.map(x=>`<div class="report" style="text-align:left"><b style="display:block;font-size:14px">📖 ${esc(x.title)}</b><small style="color:var(--muted);text-transform:capitalize">${esc(x.level)} · ${x.minutes} min</small><div class="actions" style="margin-top:10px"><button type="button" class="btn" data-reading-id="${x.id}">Start reading →</button></div></div>`).join('')||'<div class="empty">No readings for this level.</div>';$$('#reading-library-list [data-reading-id]').forEach(b=>b.addEventListener('click',()=>openReadingEntry(b.dataset.readingId)))}
function setReadingFilter(level){readingLibraryFilter=level;$$('#reading-filter-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.level===level));renderReadingLibraryList()}
async function openReadingEntry(entryId){state.readingEntryId=entryId;$('reading-library-view').style.display='none';$('reading-practice-view').style.display='block';$('reading-text').textContent='Loading reading...';$('reading-time').textContent='';$('reading-answer').value='';$('reading-result').style.display='none';try{const d=await jsonFetch('/api/reading/library/'+entryId);state.reading=d;$('reading-text').textContent=d.texto||'';const words=(d.texto||'').trim().split(/\s+/).filter(Boolean).length;$('reading-time').textContent=words?`⏱ ${Math.max(1,Math.round(words/200))} min read`:''}catch(e){toast(e.message)}}
function regenerateReading(){if(state.readingEntryId)openReadingEntry(state.readingEntryId);else loadReading()}
async function loadReading(){try{const d=await jsonFetch('/nuevo-texto-lectura');state.reading=d;$('reading-text').textContent=d.texto||'';const words=(d.texto||'').trim().split(/\s+/).filter(Boolean).length;$('reading-time').textContent=words?`⏱ ${Math.max(1,Math.round(words/200))} min read`:'';$('reading-answer').value='';$('reading-result').style.display='none'}catch(e){toast(e.message)}}
async function evaluateReading(){if(!state.reading)return toast('Load a reading first.');const answer=$('reading-answer').value.trim();if(!answer)return toast('Explain what you understood first.');busy('reading-submit',true,'Analyzing...');try{const d=await jsonFetch('/evaluar-lectura',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto_original:state.reading.texto,respuesta:answer})});$('r-score').textContent=Math.round(d.puntuacion||0);$('r-accuracy').textContent=Math.round(d.precision||0);$('r-language').textContent=Math.round(d.calidad_ingles||d.gramatica||0);$('r-vocab').textContent=Math.round(d.vocabulario||0);$('r-summary').textContent=d.resumen||'';$('r-good').innerHTML=(d.aciertos||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('r-improve').innerHTML=(d.mejoras||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('r-vocab-list').innerHTML=(d.vocabulario_sugerido||[]).map(x=>`<div class="vocab-item"><b>${esc(x.palabra||x.term||'')}</b><p>${esc(x.significado||x.meaning||'')}</p><button type="button" class="btn vocab-save-btn" style="margin-top:6px;padding:0 8px;min-height:26px;font-size:10px" data-word="${esc(x.palabra||x.term||'')}" data-meaning="${esc(x.significado||x.meaning||'')}">+ Save</button></div>`).join('');$('reading-result').style.display='block';reactToScore(d.puntuacion);renderCoachInsight('reading-coach',[{label:'Accuracy',value:d.precision},{label:'English quality',value:d.calidad_ingles||d.gramatica},{label:'Vocabulary',value:d.vocabulario}],[{label:'🔄 Try a new reading',fn:regenerateReading},{label:'📍 Practice in Learning Path',fn:()=>goToLearningPathFor('reading')}])}catch(e){toast(e.message)}finally{busy('reading-submit',false,'Analyze comprehension')}}
let listeningLibraryItems=[];
let listeningLibraryFilter='all';
async function loadListeningLibrary(){$('listening-library-view').style.display='block';$('listening-practice-view').style.display='none';$('listening-library-list').innerHTML='<div class="empty">Loading...</div>';try{const d=await jsonFetch('/api/listening/library');listeningLibraryItems=d.items||[];renderListeningLibraryList()}catch(e){$('listening-library-list').innerHTML='<div class="empty">Could not load the library.</div>';toast(e.message)}}
function renderListeningLibraryList(){const items=listeningLibraryItems.filter(x=>listeningLibraryFilter==='all'||x.level===listeningLibraryFilter);$('listening-library-list').innerHTML=items.map(x=>`<div class="report" style="text-align:left"><b style="display:block;font-size:14px">🎧 ${esc(x.title)}</b><small style="color:var(--muted);text-transform:capitalize">${esc(x.level)}</small><div class="actions" style="margin-top:10px"><button type="button" class="btn" data-listening-id="${x.id}">Start →</button></div></div>`).join('')||'<div class="empty">No audios for this level.</div>';$$('#listening-library-list [data-listening-id]').forEach(b=>b.addEventListener('click',()=>openListeningEntry(b.dataset.listeningId)))}
function setListeningFilter(level){listeningLibraryFilter=level;$$('#listening-filter-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.level===level));renderListeningLibraryList()}
async function openListeningEntry(entryId){state.listeningEntryId=entryId;$('listening-library-view').style.display='none';$('listening-practice-view').style.display='block';state.playCount=0;$('listen-playcount').textContent='🎧 0 plays';$('dictation-hint').textContent='Press play, then write what you heard.';$('dictation-answer').value='';$('dictation-result').style.display='none';try{const d=await jsonFetch('/api/listening/library/'+entryId);state.dictation=d.texto||''}catch(e){toast(e.message)}}
function regenerateListening(){if(state.listeningEntryId)openListeningEntry(state.listeningEntryId);else loadDictation()}
async function loadDictation(){try{const d=await jsonFetch('/nuevo-dictado');state.dictation=d.texto||'';state.playCount=0;$('listen-playcount').textContent='🎧 0 plays';$('dictation-hint').textContent='Press play, then write what you heard.';$('dictation-answer').value='';$('dictation-result').style.display='none'}catch(e){toast(e.message)}}
function playDictation(){if(!state.dictation)return toast('Load a dictation first.');speak(state.dictation,.9);state.playCount=(state.playCount||0)+1;$('listen-playcount').textContent=`🎧 ${state.playCount} play${state.playCount===1?'':'s'}`}
async function evaluateDictation(){const answer=$('dictation-answer').value.trim();if(!answer)return toast('Write what you heard first.');busy('dictation-submit',true,'Evaluating...');try{const d=await jsonFetch('/evaluar-dictado',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto_original:state.dictation,respuesta:answer})});$('d-score').textContent=Math.round(d.puntuacion||0);$('d-words').textContent=d.palabras_correctas??0;$('d-errors').textContent=d.diferencias??0;$('d-level').textContent=d.nivel||'—';$('d-feedback').textContent=d.feedback||'';$('dictation-result').style.display='block';reactToScore(d.puntuacion);renderCoachInsight('dictation-coach',[{label:'Listening accuracy',value:d.puntuacion}],[{label:'🔄 Try a new audio',fn:regenerateListening},{label:'📍 Practice in Learning Path',fn:()=>goToLearningPathFor('dictado')}])}catch(e){toast(e.message)}finally{busy('dictation-submit',false,'Evaluate listening')}}
function addCallMessage(text,who){const wrap=$('call-messages');const div=document.createElement('div');div.className='msg '+(who==='user'?'user':'ai');div.textContent=text;wrap.appendChild(div);wrap.scrollTop=wrap.scrollHeight}
async function callStartTalk(){if(state.callBusy)return;if(!navigator.mediaDevices?.getUserMedia)return toast('Tu navegador no soporta grabación de audio.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});let mime='audio/webm';if(window.MediaRecorder&&MediaRecorder.isTypeSupported){if(!MediaRecorder.isTypeSupported(mime)){const alternatives=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];mime=alternatives.find(x=>MediaRecorder.isTypeSupported(x))||''}}state.callChunks=[];state.callRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);state.callRecorder.ondataavailable=e=>{if(e.data.size)state.callChunks.push(e.data)};state.callRecorder.onstop=callSendTurn;state.callRecorder.start();$('call-talk-btn').classList.add('recording');$('call-status').textContent='Escuchando... suelta cuando termines'}catch(e){toast('Error de micrófono: '+e.message)}}
function callStopTalk(){$('call-talk-btn').classList.remove('recording');if(state.callRecorder&&state.callRecorder.state!=='inactive'){state.callRecorder.stop();state.callRecorder.stream?.getTracks().forEach(t=>t.stop())}}
async function callSendTurn(){const blob=new Blob(state.callChunks,{type:state.callChunks[0]?.type||'audio/webm'});if(!blob.size){$('call-status').textContent='Mantén presionado el botón para hablar';return}state.callBusy=true;$('call-status').textContent='Transcribiendo...';const fd=new FormData();fd.append('audio',blob,'call.webm');try{const t=await jsonFetch('/api/transcribir-audio',{method:'POST',body:fd});const said=(t.texto||'').trim();if(!said){$('call-status').textContent='No te escuché bien, intenta de nuevo';state.callBusy=false;return}addCallMessage(said,'user');state.callMessages.push({role:'user',content:said});$('call-status').textContent='Palanqueta está pensando...';const d=await jsonFetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mensaje:said,history:state.callMessages.slice(-14),modo:'llamada'})});const reply=d.respuesta||'';addCallMessage(reply,'ai');state.callMessages.push({role:'assistant',content:reply});await callPlayReply(reply)}catch(e){toast(e.message)}finally{$('call-status').textContent='Mantén presionado el botón para hablar';state.callBusy=false}}
async function callPlayReply(text){if(!text)return;$('call-status').textContent='Palanqueta está hablando...';startMascotTalking();try{const r=await authFetch('/api/sintetizar-audio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto:text,voz:'en-US-AvaMultilingualNeural'})});if(!r.ok)throw new Error('voz no disponible');const blob=await r.blob();const url=URL.createObjectURL(blob);const audio=new Audio(url);await new Promise(res=>{audio.onended=res;audio.onerror=res;audio.play()});URL.revokeObjectURL(url)}catch(e){speak(text)}finally{stopMascotTalking()}}
async function endCall(){vadStop();if(!state.callMessages||!state.callMessages.length)return toast('Todavía no has hablado con Palanqueta.');callStopTalk();$('call-status').textContent='Generando resumen...';try{const d=await jsonFetch('/api/resumen-llamada',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({history:state.callMessages})});$('call-score-general').textContent=Math.round(d.puntuacion_general||0);$('call-score-fluency').textContent=Math.round(d.fluidez||0);$('call-score-grammar').textContent=Math.round(d.gramatica||0);$('call-score-vocab').textContent=Math.round(d.vocabulario||0);$('call-score-pron').textContent=Math.round(d.pronunciacion_estimada||0);$('call-summary-general').textContent=d.resumen_general||'';$('call-summary-strengths').innerHTML=(d.fortalezas||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('call-summary-errors').innerHTML=(d.errores_comunes||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('call-summary-vocab').innerHTML=(d.vocabulario_recomendado||[]).map(v=>`<div class="vocab-item"><b>${esc(v.palabra||'')}</b><p>${esc(v.significado||'')}</p></div>`).join('');$('call-summary-next').textContent=d.siguiente_paso||'';$('call-summary').style.display='block';state.callMessages=[];$('call-messages').innerHTML='<div class="msg ai">Hi! I\'m Palanqueta. Press and hold the button, say something, and let go when you\'re done.</div>'}catch(e){toast(e.message)}finally{$('call-status').textContent='Mantén presionado el botón para hablar'}}
async function loadDashboard(){loadNextStep();try{const email=(state.user&&state.user.email)||'';const name=state.username||email.split('@')[0]||'there';const hour=new Date().getHours();const greet=hour<12?'Good morning':hour<19?'Good afternoon':'Good evening';$('home-greeting').textContent=`${greet}, ${esc(name)}! 👋`;const d=await jsonFetch('/api/dashboard');$('home-streak').textContent=`🔥 ${d.streak_days} day streak`;$('home-xp').textContent=`⭐ ${d.xp} XP · Level ${d.level}`;$('home-goal-pct').textContent=d.daily_goal_pct+'%';$('home-goal-fill').style.width=d.daily_goal_pct+'%';$('home-week').innerHTML=(d.week||[]).map(w=>`<div class="day-chip${w.active?' active':''}${w.is_today?' today':''}"><div class="dot">${w.active?'🔥':''}</div><small>${esc(w.weekday)}</small></div>`).join('');const labels={speaking:'🗣️ Speaking',listening:'🎧 Listening',reading:'📖 Reading',writing:'✍️ Writing'};$('home-skills').innerHTML=Object.entries(d.skills||{}).map(([k,v])=>`<div class="report" style="--v:${v}%"><b>${v}%</b><small>${labels[k]||k}</small></div>`).join('');try{const a=await jsonFetch('/api/achievements');$('home-achievements').innerHTML=a.achievements.slice(0,4).map(x=>`<div class="report ach-card${x.unlocked?' unlocked':''}"><div class="ach-icon">${x.icon}</div><small style="display:block;margin-top:4px">${esc(x.title)}</small></div>`).join('')}catch(e){}
try{const vd=await jsonFetch('/api/vocabulario/diario');const w=(vd.palabras||[])[0];$('home-vocab-word').innerHTML=w?`<b style="font-size:16px">${esc(w.palabra)}</b><p style="margin:4px 0;color:var(--muted);font-size:12px">${esc(w.significado||'')}</p>${w.ejemplo?`<p style="font-style:italic;font-size:12px">"${esc(w.ejemplo)}"</p>`:''}`:'<div class="empty">No words yet.</div>'}catch(e){$('home-vocab-word').innerHTML='<div class="empty">Could not load today\'s word.</div>'}
try{const vl=await jsonFetch('/api/vocabulario');const pct=vl.total?Math.round(vl.aprendidas/vl.total*100):0;$('home-vocab-stats').innerHTML=`<small style="color:var(--muted)">Your vocabulary</small><div style="font-weight:700;font-size:15px;margin:2px 0">${vl.aprendidas} / ${vl.total} learned</div><div class="bar" style="margin-top:6px"><div class="fill" style="width:${pct}%"></div></div><button type="button" class="btn" id="home-vocab-review-btn" style="margin-top:8px">Review words →</button>`;$('home-vocab-review-btn')?.addEventListener('click',()=>{section('vocabulario');closeSidebar()})}catch(e){}}catch(e){console.error('[DASHBOARD]',e)}}
async function loadAchievements(){try{const d=await jsonFetch('/api/achievements');$('ach-count').textContent=`🏆 ${d.unlocked_count} / ${d.achievements.length} unlocked`;$('ach-list').innerHTML=d.achievements.map(a=>`<div class="report ach-card${a.unlocked?' unlocked':''}"><div class="ach-icon">${a.icon}</div><b style="display:block;margin-top:6px;font-size:13px">${esc(a.title)}</b>${a.unlocked?'<small style="color:var(--success)">✓ Completed</small>':`<div class="bar"><div class="fill" style="width:${a.progress}%"></div></div><small>${a.progress}%</small>`}</div>`).join('')}catch(e){toast(e.message)}}
async function loadVocabDaily(){$('vocab-daily').innerHTML='<div class="empty">Loading...</div>';try{const d=await jsonFetch('/api/vocabulario/diario');$('vocab-daily').innerHTML=d.palabras.map(w=>`<div class="vocab-item" style="margin-bottom:8px"><b>${esc(w.palabra)}</b><p>${esc(w.significado||'')}</p>${w.ejemplo?`<p style="font-style:italic">"${esc(w.ejemplo)}"</p>`:''}<div class="actions" style="justify-content:flex-start;margin-top:6px;gap:6px"><button type="button" class="btn" style="padding:0 8px;min-height:26px;font-size:10px" onclick="playGuideAudio(${JSON.stringify(w.palabra)},this.id||'vocab-refresh')">🔊</button></div></div>`).join('')||'<div class="empty">No words yet.</div>';loadVocabList()}catch(e){$('vocab-daily').innerHTML='<div class="empty">Could not load today\'s words.</div>'}}
async function loadVocabList(){try{const d=await jsonFetch('/api/vocabulario');$('vocab-total').textContent=`📚 ${d.total} words saved`;$('vocab-learned').textContent=`✅ ${d.aprendidas} learned`;$('vocab-list').innerHTML=d.palabras.map(w=>`<div class="history-card"><div class="history-head"><span>${esc(w.palabra)}</span><button type="button" class="btn vocab-toggle-btn" style="padding:0 8px;min-height:24px;font-size:10px" data-id="${w.id}" data-state="${w.aprendida}">${w.aprendida?'✓ Learned':'Mark learned'}</button></div><div class="history-meta"><span>${esc(w.significado||'')}</span><span>${esc(w.origen||'')}</span></div></div>`).join('')||'<div class="empty">No saved words yet.</div>'}catch(e){toast(e.message)}}
let lpState={units:[],currentUnit:null,topics:[],currentTopicId:null,currentTool:null,currentExercise:null,recorder:null,chunks:[],recording:false};
async function loadLearningPath(){$('lp-topics-view').style.display='none';$('lp-units-view').style.display='block';$('lp-units').innerHTML='<div class="empty">Loading...</div>';try{const d=await jsonFetch('/api/learning-path');lpState.units=d.units;$('lp-xp').textContent=`⭐ ${d.xp} XP`;let currentAssigned=false;$('lp-units').innerHTML=d.units.map((u,i)=>{const pct=u.total_topics?Math.round(u.completed_topics/u.total_topics*100):0;const locked=!u.unlocked;const isCurrent=!locked&&!u.completed&&!currentAssigned;if(isCurrent)currentAssigned=true;const state=locked?'locked':(u.completed?'completed':(isCurrent?'current':''));const align=i%2===0?'align-left':'align-right';const connector=i>0?'<div class="lp-connector"></div>':'';const icon=locked?'🔒':(u.completed?'✓':u.icon);return `<div class="lp-node ${align}">${connector}<div class="lp-circle ${state}" ${locked?'':`onclick="openLearningUnit('${u.code}')"`}>${icon}</div><div class="lp-node-label"><b style="display:block;font-size:14px">${esc(u.title)}</b>${locked?`<small style="color:var(--muted)">Requires ${u.xp_required} XP${u.order>1?' + previous unit':''}</small>`:`<small style="color:var(--muted)">${u.completed_topics}/${u.total_topics} lessons${u.completed?' · Completed 🎉':''}</small><div class="bar" style="margin-top:6px;width:140px"><div class="fill" style="width:${pct}%"></div></div>`}</div></div>`}).join('')}catch(e){$('lp-units').innerHTML='<div class="empty">Could not load your learning path.</div>';toast(e.message)}}
function renderLPTopics(){$('lp-topics').innerHTML=lpState.topics.map(t=>`<div class="report" style="text-align:left;cursor:pointer" onclick="openLearningTopic('${t.id}')"><b style="display:block;font-size:13px">${esc(t.title)}</b>${t.completed?'<small style="color:var(--success)">✓ Completed</small>':'<small>Not started</small>'}</div>`).join('')}
async function openLearningUnit(code){try{const d=await jsonFetch('/api/learning-path/'+code);lpState.currentUnit={...d.unit,code};lpState.topics=d.topics;$('lp-units-view').style.display='none';$('lp-topics-view').style.display='block';$('lp-unit-title').textContent=d.unit.icon+' '+d.unit.title;$('lp-unit-desc').textContent=d.unit.description;renderLPTopics();$('lp-tool-picker').style.display='none';$('lp-practice-area').innerHTML=''}catch(e){toast(e.message)}}
function backToLPUnits(){$('lp-topics-view').style.display='none';$('lp-units-view').style.display='block';loadLearningPath()}
function openLearningTopic(topicId){lpState.currentTopicId=topicId;const t=lpState.topics.find(x=>x.id===topicId);$('lp-tool-picker').style.display='block';$('lp-tool-picker-title').textContent=`How do you want to practice "${t.title}"?`;$('lp-practice-area').innerHTML=''}
function markLPTopicDone(){const t=lpState.topics.find(x=>x.id===lpState.currentTopicId);if(t)t.completed=true;renderLPTopics()}
function renderLPProgressBanner(lp){if(!lp)return '';if(lp.newly_completed)return `<div class="notice" style="margin-top:10px;color:var(--success)">🎉 Topic completed! +30 XP${lp.unit_completed?' · 🏆 Unit completed!':''}</div>`;if(lp.passed)return '<div class="notice" style="margin-top:10px">✓ Already completed.</div>';return '<div class="notice" style="margin-top:10px">Keep practicing — you need at least 60% to complete this topic.</div>'}
async function startLearningPractice(tool){lpState.currentTool=tool;$('lp-practice-area').innerHTML='<div class="empty">Preparing your exercise...</div>';try{const d=await jsonFetch('/api/learning-path/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unit_code:lpState.currentUnit.code,topic_id:lpState.currentTopicId,tool})});lpState.currentExercise=d;renderLearningPractice(tool,d)}catch(e){$('lp-practice-area').innerHTML='';toast(e.message)}}
function renderLearningPractice(tool,d){if(tool==='pronunciation'){$('lp-practice-area').innerHTML=`<div class="card"><p style="font-size:11px;color:var(--muted)">Say this out loud:</p><p style="font-size:18px;font-weight:600;margin:8px 0">${esc(d.texto)}</p><div class="actions" style="justify-content:flex-start"><button type="button" class="btn primary" id="lp-record-btn" onclick="toggleLPRecording()">Start recording</button></div><div id="lp-practice-result"></div></div>`}else if(tool==='writing'){$('lp-practice-area').innerHTML=`<div class="card"><p style="font-size:11px;color:var(--muted)">Writing challenge:</p><p style="font-size:14px;font-weight:600;margin:8px 0">${esc(d.prompt)}</p><textarea id="lp-writing-input" placeholder="Write in English..."></textarea><div class="actions" style="margin-top:8px"><button type="button" class="btn primary" onclick="submitLPWriting()">Analyze writing</button></div><div id="lp-practice-result"></div></div>`}else if(tool==='reading'){$('lp-practice-area').innerHTML=`<div class="card"><p style="font-size:11px;color:var(--muted)">${esc(d.titulo||'Reading')}</p><div class="reading" style="margin:8px 0">${esc(d.texto)}</div><label class="field-label">Explain what you understood, in English</label><textarea id="lp-reading-input" placeholder="Write your explanation..."></textarea><div class="actions" style="margin-top:8px"><button type="button" class="btn primary" onclick="submitLPReading()">Submit</button></div><div id="lp-practice-result"></div></div>`}else if(tool==='dictado'){$('lp-practice-area').innerHTML=`<div class="card"><p style="font-size:11px;color:var(--muted)">Listen carefully, then type what you hear.</p><div class="actions" style="justify-content:flex-start"><button type="button" class="btn" onclick="speak(lpState.currentExercise.texto,.9)">🔊 Play</button></div><textarea id="lp-dictation-input" placeholder="Type what you heard..." style="margin-top:8px"></textarea><div class="actions" style="margin-top:8px"><button type="button" class="btn primary" onclick="submitLPDictation()">Submit</button></div><div id="lp-practice-result"></div></div>`}}
function toggleLPRecording(){const b=$('lp-record-btn');if(lpState.recording){lpState.recording=false;b.textContent='Analyzing...';b.disabled=true;try{lpState.recorder.stop();lpState.recorder.stream?.getTracks().forEach(t=>t.stop())}catch(e){toast('Recording could not be stopped.')}}else{if(!navigator.mediaDevices?.getUserMedia)return toast('Your browser does not support microphone recording.');navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{let mime='audio/webm';if(window.MediaRecorder&&MediaRecorder.isTypeSupported&&!MediaRecorder.isTypeSupported(mime)){const alts=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];mime=alts.find(x=>MediaRecorder.isTypeSupported(x))||''}lpState.chunks=[];lpState.recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);lpState.recorder.ondataavailable=e=>{if(e.data.size)lpState.chunks.push(e.data)};lpState.recorder.onstop=sendLPRecording;lpState.recorder.start();lpState.recording=true;b.textContent='Recording... click to stop'}).catch(e=>toast('Microphone error: '+e.message))}}
async function sendLPRecording(){const blob=new Blob(lpState.chunks,{type:lpState.chunks[0]?.type||'audio/webm'});const fd=new FormData();fd.append('audio',blob,'recording.webm');fd.append('frase_esperada',lpState.currentExercise.texto||'');fd.append('unit_code',lpState.currentUnit.code);fd.append('topic_id',lpState.currentTopicId);try{const d=await jsonFetch('/analizar-audio-real',{method:'POST',body:fd});$('lp-practice-result').innerHTML=`<div class="report-grid" style="margin-top:10px"><div class="report"><b>${Math.round(d.puntuacion_global||0)}</b><small>Overall</small></div><div class="report"><b>${Math.round(d.precision||0)}</b><small>Accuracy</small></div><div class="report"><b>${Math.round(d.fluidez||0)}</b><small>Fluency</small></div></div>${renderLPProgressBanner(d.learning_path)}`;if(d.learning_path&&d.learning_path.newly_completed)markLPTopicDone()}catch(e){toast(e.message)}finally{const b=$('lp-record-btn');if(b){b.textContent='Start recording';b.disabled=false}}}
async function submitLPWriting(){const text=$('lp-writing-input').value.trim();if(!text)return toast('Write something first.');try{const d=await jsonFetch('/analizar-escritura',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto:text,unit_code:lpState.currentUnit.code,topic_id:lpState.currentTopicId})});$('lp-practice-result').innerHTML=`<div class="report-grid" style="margin-top:10px"><div class="report"><b>${Math.round(d.puntuacion||0)}</b><small>Overall</small></div><div class="report"><b>${Math.round(d.gramatica||0)}</b><small>Grammar</small></div><div class="report"><b>${Math.round(d.vocabulario||0)}</b><small>Vocabulary</small></div></div>${renderLPProgressBanner(d.learning_path)}`;if(d.learning_path&&d.learning_path.newly_completed)markLPTopicDone()}catch(e){toast(e.message)}}
async function submitLPReading(){const answer=$('lp-reading-input').value.trim();if(!answer)return toast('Explain what you understood first.');try{const d=await jsonFetch('/evaluar-lectura',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto_original:lpState.currentExercise.texto,respuesta:answer,unit_code:lpState.currentUnit.code,topic_id:lpState.currentTopicId})});$('lp-practice-result').innerHTML=`<div class="report-grid" style="margin-top:10px"><div class="report"><b>${Math.round(d.puntuacion||0)}</b><small>Overall</small></div><div class="report"><b>${Math.round(d.claridad||0)}</b><small>Clarity</small></div><div class="report"><b>${Math.round(d.vocabulario||0)}</b><small>Vocabulary</small></div></div>${renderLPProgressBanner(d.learning_path)}`;if(d.learning_path&&d.learning_path.newly_completed)markLPTopicDone()}catch(e){toast(e.message)}}
async function submitLPDictation(){const answer=$('lp-dictation-input').value.trim();if(!answer)return toast('Type what you heard first.');try{const d=await jsonFetch('/evaluar-dictado',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto_original:lpState.currentExercise.texto,respuesta:answer,unit_code:lpState.currentUnit.code,topic_id:lpState.currentTopicId})});$('lp-practice-result').innerHTML=`<div class="report-grid" style="margin-top:10px"><div class="report"><b>${Math.round(d.puntuacion||0)}</b><small>Score</small></div><div class="report"><b>${d.palabras_correctas??0}</b><small>Correct words</small></div><div class="report"><b>${d.diferencias??0}</b><small>Differences</small></div></div>${renderLPProgressBanner(d.learning_path)}`;if(d.learning_path&&d.learning_path.newly_completed)markLPTopicDone()}catch(e){toast(e.message)}}
async function saveVocabWord(palabra,significado,origen){try{await jsonFetch('/api/vocabulario/guardar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({palabra,significado,origen})});toast('Saved to your vocabulary.');loadVocabList()}catch(e){toast(e.message)}}
async function toggleVocabLearned(id,current){try{await jsonFetch('/api/vocabulario/marcar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,aprendida:!current})});loadVocabList()}catch(e){toast(e.message)}}
const FRAME_GRADIENTS={gold:'linear-gradient(135deg,#f5c542,#ffb37a)',fire:'linear-gradient(135deg,#ff6b4a,#ff3d6e)',ocean:'linear-gradient(135deg,#4ad0ff,#7180ff)'};
function avatarMarkup(url,initials,frameGradient){const inner=url?`<img src="${esc(url)}" alt="" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`:esc(initials);if(!frameGradient)return inner;return `<div style="width:100%;height:100%;border-radius:50%;padding:3px;background:${frameGradient};display:flex;align-items:center;justify-content:center;box-sizing:border-box"><div style="width:100%;height:100%;border-radius:50%;overflow:hidden;background:var(--bg);display:flex;align-items:center;justify-content:center">${inner}</div></div>`}
function applyProfileIdentity(user,d){const u=(d&&d.user)||{};state.username=u.username||'';state.avatarFrame=u.avatar_frame||'';const name=u.username||user.email||'Signed in';const initials=(u.username||user.email||'T').trim().slice(0,2).toUpperCase();const frameGrad=FRAME_GRADIENTS[u.avatar_frame]||null;$('user-display').textContent=name;$('side-email').textContent=u.username||user.email||'Student';$('side-avatar').innerHTML=avatarMarkup(u.avatar_url,initials,frameGrad);$('profile-avatar-preview').innerHTML=avatarMarkup(u.avatar_url,initials,frameGrad);$('profile-username').value=u.username||''}
async function saveUsername(){const name=$('profile-username').value.trim();if(name.length<2)return toast('Escribe al menos 2 caracteres.');busy('profile-username-save',true,'Saving...');try{await jsonFetch('/api/perfil',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name})});$('user-display').textContent=name;$('side-email').textContent=name;toast('Nombre actualizado.')}catch(e){toast(e.message)}finally{busy('profile-username-save',false,'Save')}}
async function uploadAvatar(file){if(!file)return;if(file.size>4*1024*1024)return toast('La imagen no debe pesar más de 4 MB.');const fd=new FormData();fd.append('avatar',file);busy('profile-avatar-btn',true,'Uploading...');try{const d=await jsonFetch('/api/perfil/avatar',{method:'POST',body:fd});const frameGrad=FRAME_GRADIENTS[state.avatarFrame]||null;$('profile-avatar-preview').innerHTML=avatarMarkup(d.avatar_url,'T',frameGrad);$('side-avatar').innerHTML=avatarMarkup(d.avatar_url,'T',frameGrad);toast('Foto actualizada.')}catch(e){toast(e.message)}finally{busy('profile-avatar-btn',false,'Upload photo')}}
function renderAccountInfo(user,d){$('acc-email').textContent=user.email||'-';const miembro=d.user&&d.user.miembro_desde?new Date(d.user.miembro_desde).toLocaleDateString():'-';$('acc-miembro').textContent=miembro;if(d.en_prueba){$('acc-plan').textContent='Prueba gratis';$('acc-plan').style.color='var(--warning)';$('acc-dias').textContent=d.trial_dias_restantes+' día(s)';$('acc-detalle').textContent='Estás en tu período de prueba gratuita. Al terminar, renueva para seguir practicando.';$('acc-renovar').style.display='none'}else if(d.is_subscribed){$('acc-plan').textContent='Activa';$('acc-plan').style.color='var(--success)';$('acc-dias').textContent='—';$('acc-detalle').textContent='Tu suscripción está activa. ¡Sigue practicando!';$('acc-renovar').style.display='none'}else{$('acc-plan').textContent='Vencida';$('acc-plan').style.color='var(--danger)';$('acc-dias').textContent='0 días';$('acc-detalle').textContent='Tu prueba o suscripción terminó. Renueva por $79 MXN/mes para seguir con acceso.';$('acc-renovar').style.display='inline-block';$('acc-renovar').href='https://wa.me/529911093870?text=Hola%2C%20ya%20hice%20mi%20pago%20de%20%2479%20MXN%2C%20aqui%20esta%20mi%20comprobante%3A'}}
async function enviarSoporte(){const tipo=$('soporte-tipo').value;const texto=$('soporte-texto').value.trim();if(!texto)return toast('Escribe tu mensaje antes de enviar.');busy('soporte-enviar',true,'Enviando...');try{await jsonFetch('/api/soporte',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tipo,mensaje:texto})});$('soporte-texto').value='';$('soporte-confirmacion').style.display='block';setTimeout(()=>$('soporte-confirmacion').style.display='none',5000)}catch(e){toast(e.message)}finally{busy('soporte-enviar',false,'Enviar mensaje')}}
function addTutorMessage(text,who){const wrap=$('tutor-messages');const div=document.createElement('div');div.className='msg '+(who==='user'?'user':'ai');div.textContent=text;wrap.appendChild(div);wrap.scrollTop=wrap.scrollHeight}
let tutorCategory='conversation';
const TUTOR_OPENERS={conversation:'Hi! I\'m Palanqueta, your English tutor. Tell me something about your day.',grammar:'Let\'s work on grammar today! Tell me about something you did last weekend — I\'ll help you get the tenses just right.',vocabulary:'Let\'s grow your vocabulary! Tell me about a hobby you enjoy, and I\'ll introduce some useful new words as we talk.',pronunciation:'Let\'s focus on pronunciation. Try saying a short sentence about yourself, and I\'ll give you tips on how it should sound.',free:'Free talk! Tell me about anything on your mind — no particular topic, just practice speaking freely.'};
function setTutorCategory(cat){tutorCategory=cat;$$('#tutor-category-bar .mode').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));$('tutor-messages').innerHTML=`<div class="msg ai">${esc(TUTOR_OPENERS[cat]||TUTOR_OPENERS.conversation)}</div>`}
async function tutorSend(text){const value=(text??$('tutor-input').value).trim();if(!value)return;addTutorMessage(value,'user');$('tutor-input').value='';busy('tutor-send',true,'Thinking...');try{const d=await jsonFetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mensaje:value,categoria:tutorCategory,history:Array.from($('tutor-messages').querySelectorAll('.msg')).slice(-8).map(m=>({role:m.classList.contains('user')?'user':'assistant',content:m.textContent}))})});addTutorMessage(d.respuesta||'Let’s keep practicing.','ai');state.lastTutor=d.respuesta||'';if(settingsAutoplay)speak(d.respuesta||'')}catch(e){toast(e.message)}finally{busy('tutor-send',false,'Send')}}
function tutorMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice input is not available in this browser.');const r=new SR();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>toast('Listening...');r.onerror=e=>toast('Voice input: '+e.error);r.onresult=e=>tutorSend(e.results[0][0].transcript);r.start()}
async function loadProgress(){try{const d=await jsonFetch('/api/progreso');$('p-total').textContent=d.total_actividades??0;$('p-pron').textContent=d.pronunciacion??0;$('p-writing').textContent=d.escritura??0;$('p-reading').textContent=d.lectura??0;const scores=d.puntuaciones_recientes||[];$('progress-bars').innerHTML=scores.map(x=>`<div class="barcol" title="${Math.round(x)}"><i style="height:${Math.max(4,Math.min(100,Number(x)||0))}%"></i></div>`).join('')||'<div class="empty">No scores yet.</div>';const h=await jsonFetch('/obtener-historial');renderHistory(h)}catch(e){toast(e.message)}}
async function renderPronTrend(){const box=$('pron-trend');if(!box)return;try{const h=await jsonFetch('/obtener-historial');const items=Array.isArray(h)?h:(h.historial||[]);const rows=items.filter(x=>(x.tipo||x.type)==='pronunciation'&&(x.puntuacion??x.score)!=null);const todayStr=new Date().toDateString();const yestStr=new Date(Date.now()-86400000).toDateString();let today='—',yesterday='—',best=0;rows.forEach(r=>{const val=Math.round(Number(r.puntuacion??r.score));const d=new Date(r.created_at||r.fecha||'');const dStr=isNaN(d)?'':d.toDateString();if(dStr===todayStr&&today==='—')today=val;if(dStr===yestStr&&yesterday==='—')yesterday=val;if(val>best)best=val});box.innerHTML=`<div class="pbox"><strong>${today}${today!=='—'?'%':''}</strong><small>Today</small></div><div class="pbox"><strong>${yesterday}${yesterday!=='—'?'%':''}</strong><small>Yesterday</small></div><div class="pbox"><strong>${best}%</strong><small>Best</small></div>`}catch(e){box.innerHTML=''}}
function renderHistory(data){const list=$('history-list');const items=Array.isArray(data)?data:(data.historial||[]);list.innerHTML=items.slice(0,30).map(x=>`<div class="history-card"><div class="history-head"><span>${esc(x.tipo||x.type||'Practice')}</span><span>${esc(x.puntuacion??x.score??'—')}</span></div><div class="history-meta"><span>${esc(x.created_at||x.fecha||'')}</span><span>${esc(x.frase||x.tema||x.resumen||'')}</span></div></div>`).join('')||'<div class="empty">Your practice history will appear here.</div>'}
async function loadAdminActivity(){try{const d=await jsonFetch('/api/admin/actividad');$('admin-total').textContent=d.total_usuarios;$('admin-prueba').textContent=d.en_prueba;$('admin-pagados').textContent=d.pagados;const list=$('admin-eventos');list.innerHTML=(d.eventos||[]).map(e=>`<div class="history-card"><div class="history-head"><span>${esc(e.tipo)}</span><span>${esc(e.email||'')}</span></div><div class="history-meta"><span>${esc(e.fecha||'')}</span><span>${esc(e.detalle||'')}</span></div></div>`).join('')||'<div class="empty">Sin actividad todavía.</div>'}catch(e){toast(e.message)}}
async function authSubmit(){const email=$('auth-email').value.trim();const password=$('auth-password').value;if(!email||!password)return authError('Enter your email and password.');busy('auth-submit',true,state.authRegister?'Creating...':'Signing in...');authError('');try{let r;if(state.authRegister){r=await sb.auth.signUp({email,password});if(r.error)throw r.error;toast(r.data.session?'Account created.':'Check your email to confirm your account.')}else{r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;closeAuth();await syncUser(r.data.user)} }catch(e){console.error('[AUTH]',e);authError(e.message||'Could not sign in.')}finally{busy('auth-submit',false,state.authRegister?'Create account':'Sign in')}}
let obAnswers={learning_goal:null,daily_goal_minutes:null,cefr_level:null};
function initOnboarding(){obAnswers={learning_goal:null,daily_goal_minutes:null,cefr_level:null};$('onboarding-view').style.display='flex';showObStep(1)}
function showObStep(n){[1,2,3,4,5].forEach(i=>{const el=$('ob-step-'+i);if(el)el.style.display=i===n?'block':'none'})}
function selectObOption(groupId,key,value,btn){$$('#'+groupId+' .ob-option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');obAnswers[key]=value;setTimeout(()=>{if(key==='learning_goal')showObStep(2);else if(key==='daily_goal_minutes')showObStep(3);else if(key==='cefr_level')finishOnboarding()},300)}
async function finishOnboarding(){try{await jsonFetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(obAnswers)})}catch(e){toast(e.message)}$('onboarding-view').style.display='none';$('app-content').style.display='block';closeAuth();loadDashboard();loadReading().catch(()=>{});loadDictation().catch(()=>{})}
function openAuthAs(register){state.authRegister=register;$('auth-title').textContent=register?'Create account':'Sign in';$('auth-submit').textContent=register?'Create account':'Sign in';$('auth-toggle').textContent=register?'Back to sign in':'Create an account';authError('');showAuth()}
function toggleAuthMode(){state.authRegister=!state.authRegister;$('auth-title').textContent=state.authRegister?'Create account':'Sign in';$('auth-submit').textContent=state.authRegister?'Create account':'Sign in';$('auth-toggle').textContent=state.authRegister?'Back to sign in':'Create an account';authError('')}
async function signOut(){await sb.auth.signOut();state.user=null;state.subscribed=false;syncUser(null)}
function openSidebar(){document.querySelector('.sidebar')?.classList.add('open');$('sidebar-overlay')?.classList.add('show');document.body.style.overflow='hidden'}
function closeSidebar(){document.querySelector('.sidebar')?.classList.remove('open');$('sidebar-overlay')?.classList.remove('show');document.body.style.overflow=''}
function bind(){
$$('#main-nav button').forEach(b=>b.addEventListener('click',()=>{section(b.dataset.section,b);closeSidebar()}));
$$('[data-section-jump]').forEach(b=>b.addEventListener('click',()=>{section(b.dataset.sectionJump);closeSidebar()}));
$('nav-toggle')?.addEventListener('click',openSidebar);
$$('#tabbar button').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.tab;if(t==='menu')openSidebar();else section(t)}));
let lastSec='';const TAB_IDS=['home','learning-path','pronunciacion','tutor'];
const syncTabs=()=>{const a=document.querySelector('.section.active');const id=a?a.id.replace('sec-',''):'home';$$('#tabbar button').forEach(b=>b.classList.toggle('active',TAB_IDS.includes(id)?b.dataset.tab===id:b.dataset.tab==='menu'));if(id!==lastSec){lastSec=id;const pg=$('app-content');if(pg)pg.scrollTop=0;window.scrollTo(0,0)}};
const secObs=new MutationObserver(syncTabs);$$('.section').forEach(sc=>secObs.observe(sc,{attributes:true,attributeFilter:['class']}));syncTabs();
$('sidebar-close')?.addEventListener('click',closeSidebar);
$('sidebar-overlay')?.addEventListener('click',closeSidebar);
$$('.mode[data-pron]').forEach(b=>b.addEventListener('click',()=>pronMode(b.dataset.pron)));
$$('#writing-level-bar .mode').forEach(b=>b.addEventListener('click',()=>setWritingLevel(b.dataset.level,b)));
$$('#tutor-category-bar .mode').forEach(b=>b.addEventListener('click',()=>setTutorCategory(b.dataset.cat)));
$$('#setting-autoplay-bar .mode').forEach(b=>b.addEventListener('click',()=>setSettingAutoplay(b.dataset.val)));
$$('#setting-rate-bar .mode').forEach(b=>b.addEventListener('click',()=>setSettingRate(b.dataset.val)));
applySettingsUI();
$('writing-new-challenge').addEventListener('click',loadWritingChallenge);
$('writing-skip-challenge').addEventListener('click',()=>{$('writing-challenge-card').style.display='none';updateWritingWordcount()});
$('login-btn').addEventListener('click',showAuth);
$('welcome-start').addEventListener('click',()=>openAuthAs(true));
$('welcome-login').addEventListener('click',()=>openAuthAs(false));
$$('#ob-goal-options .ob-option').forEach(b=>b.addEventListener('click',()=>selectObOption('ob-goal-options','learning_goal',b.dataset.val,b)));
$$('#ob-time-options .ob-option').forEach(b=>b.addEventListener('click',()=>selectObOption('ob-time-options','daily_goal_minutes',parseInt(b.dataset.val,10),b)));
$$('#ob-level-options .ob-option').forEach(b=>b.addEventListener('click',()=>selectObOption('ob-level-options','cefr_level',b.dataset.val,b)));
$('profile-username-save').addEventListener('click',saveUsername);
$('shop-buy-freeze').addEventListener('click',()=>buyItem('streak_freeze'));
$('profile-avatar-btn').addEventListener('click',()=>$('profile-avatar-input').click());
$('profile-avatar-input').addEventListener('change',e=>uploadAvatar(e.target.files[0]));$('logout-btn').addEventListener('click',signOut);$('locked-login').addEventListener('click',showAuth);$('auth-close').addEventListener('click',closeAuth);$('auth-submit').addEventListener('click',authSubmit);$('auth-forgot').addEventListener('click',forgotPassword);$('reset-submit').addEventListener('click',resetSubmit);$('reset-password').addEventListener('keydown',e=>{if(e.key==='Enter')resetSubmit()});$('auth-toggle').addEventListener('click',toggleAuthMode);$('auth-password').addEventListener('keydown',e=>{if(e.key==='Enter')authSubmit()});$('use-custom').addEventListener('click',customPhrase);$('new-phrase').addEventListener('click',newPhrase);$('listen-phrase').addEventListener('click',()=>playGuideAudio($('phrase').textContent.trim(),'listen-phrase'));$('new-topic').addEventListener('click',newTopic);$('new-twister').addEventListener('click',newTwister);$('listen-twister').addEventListener('click',()=>playGuideAudio($('twister').textContent.trim(),'listen-twister'));$('record-btn').addEventListener('click',toggleRecording);$('writing-submit').addEventListener('click',analyzeWriting);$('writing').addEventListener('input',updateWritingWordcount);$('reading-new').addEventListener('click',regenerateReading);$('reading-submit').addEventListener('click',evaluateReading);
$$('#reading-filter-bar .mode').forEach(b=>b.addEventListener('click',()=>setReadingFilter(b.dataset.level)));
$('reading-back-to-library').addEventListener('click',loadReadingLibrary);
$$('#listening-filter-bar .mode').forEach(b=>b.addEventListener('click',()=>setListeningFilter(b.dataset.level)));
$('listening-back-to-library').addEventListener('click',loadListeningLibrary);$('listen-play').addEventListener('click',playDictation);$('listen-new').addEventListener('click',regenerateListening);$('dictation-submit').addEventListener('click',evaluateDictation);$('tutor-send').addEventListener('click',()=>tutorSend());$('tutor-input').addEventListener('keydown',e=>{if(e.key==='Enter')tutorSend()});$('tutor-mic').addEventListener('click',tutorMic);$('tutor-speak').addEventListener('click',()=>speak(state.lastTutor||'Keep practicing.'));$('call-talk-btn').addEventListener('mousedown',callStartTalk);$('call-talk-btn').addEventListener('touchstart',e=>{e.preventDefault();callStartTalk()});$('call-talk-btn').addEventListener('mouseup',callStopTalk);$('call-talk-btn').addEventListener('mouseleave',callStopTalk);$('call-talk-btn').addEventListener('touchend',e=>{e.preventDefault();callStopTalk()});$('call-hangup').addEventListener('click',endCall);$('soporte-enviar').addEventListener('click',enviarSoporte);$('mascot').addEventListener('click',mascotClicked);$('vocab-refresh').addEventListener('click',loadVocabDaily);document.addEventListener('click',e=>{const save=e.target.closest('.vocab-save-btn');if(save){saveVocabWord(save.dataset.word,save.dataset.meaning,'lectura');return}const tog=e.target.closest('.vocab-toggle-btn');if(tog){toggleVocabLearned(tog.dataset.id,tog.dataset.state==='true')}});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeAuth()})}

/* ===== Talvo extras: siguiente paso, repaso, manos libres, prueba de nivel ===== */
try{fetch(API_URL+'/health',{cache:'no-store'}).catch(()=>{})}catch(e){}

async function loadNextStep(){
  const t=$('home-next-title'),l=$('home-next-label');if(!t||!l)return;
  try{
    const d=await jsonFetch('/api/learning-path');const units=d.units||[];
    const unit=units.find(u=>u.unlocked&&!u.completed)||units.find(u=>u.unlocked)||units[0];
    if(!unit)throw new Error('none');
    const det=await jsonFetch('/api/learning-path/'+unit.code);
    const topic=(det.topics||[]).find(x=>!x.completed)||(det.topics||[])[0];
    state.next={unit:unit.code,topic:topic?topic.id:null};
    l.textContent='Continue · '+(unit.completed_topics||0)+'/'+(unit.total_topics||0)+' lessons';
    t.textContent=((unit.icon||'')+' '+(unit.title||'')+(topic?' — '+topic.title:'')).trim();
  }catch(e){state.next=null;l.textContent='Next step';t.textContent='Start with a free practice'}
}
async function continueLearning(){
  if(!state.next){section('pronunciacion');return}
  section('learning-path');
  try{await openLearningUnit(state.next.unit);if(state.next.topic)await openLearningTopic(state.next.topic)}catch(e){toast(e.message)}
}
$('home-next')?.addEventListener('click',continueLearning);

/* --- repaso espaciado (se guarda en este dispositivo) --- */
const SRS_DAYS=[0,1,3,7,14,30];
function srsKey(){return 'talvo_srs_'+((state.user&&state.user.id)||'anon')}
function srsLoad(){try{return JSON.parse(localStorage.getItem(srsKey())||'{}')}catch(e){return {}}}
function srsSave(m){try{localStorage.setItem(srsKey(),JSON.stringify(m))}catch(e){}}
let srsWords=[],srsQueue=[],srsIdx=0;
async function refreshSrs(){
  const cnt=$('srs-count'),btn=$('srs-start');if(!cnt)return;
  try{const d=await jsonFetch('/api/vocabulario');srsWords=d.palabras||[]}catch(e){srsWords=[]}
  const m=srsLoad(),now=Date.now();
  srsQueue=srsWords.filter(w=>{const r=m[w.id];return !r||r.due<=now});
  if($('srs-session').style.display==='block')return;
  if(srsQueue.length){cnt.textContent=srsQueue.length+(srsQueue.length===1?' word due today':' words due today');btn.style.display=''}
  else{cnt.textContent=srsWords.length?'Nothing to review right now':'Save words from your readings and daily list to review them here.';btn.style.display='none'}
}
function srsShow(){
  const w=srsQueue[srsIdx];if(!w){srsFinish();return}
  $('srs-word').textContent=w.palabra||'';$('srs-meaning').textContent='';
  $('srs-reveal-row').style.display='flex';$('srs-grade-row').style.display='none';
  $('srs-pos').textContent=(srsIdx+1)+' / '+srsQueue.length;
  $('srs-fill').style.width=Math.round(srsIdx/srsQueue.length*100)+'%';
}
function srsFinish(){
  $('srs-session').style.display='none';
  $('srs-count').textContent='Review done!';$('srs-start').style.display='none';
  toast('Come back tomorrow for more.');
}
function srsGrade(g){
  const w=srsQueue[srsIdx];if(!w)return;
  const m=srsLoad(),r=m[w.id]||{box:w.aprendida?2:0};
  const box=g==='again'?0:Math.min(5,r.box+(g==='easy'?2:1));
  m[w.id]={box,due:g==='again'?Date.now()+10*60*1000:Date.now()+SRS_DAYS[box]*86400000};
  srsSave(m);
  if(g==='again')srsQueue.push(w);
  srsIdx++;srsShow();
}
$('srs-start')?.addEventListener('click',()=>{srsIdx=0;$('srs-session').style.display='block';$('srs-start').style.display='none';srsShow()});
$('srs-reveal')?.addEventListener('click',()=>{const w=srsQueue[srsIdx];if(!w)return;$('srs-meaning').textContent=w.significado||'';$('srs-reveal-row').style.display='none';$('srs-grade-row').style.display='flex'});
$('srs-hear')?.addEventListener('click',()=>{const w=srsQueue[srsIdx];if(w)speak(w.palabra)});
$$('#srs-grade-row [data-grade]').forEach(b=>b.addEventListener('click',()=>srsGrade(b.dataset.grade)));

/* --- practicar una palabra suelta --- */
$('phoneme-hear')?.addEventListener('click',()=>{if(state.phWord)speak(state.phWord)});
$('phoneme-practice')?.addEventListener('click',()=>{
  if(!state.phWord)return;
  pronMode('lectura');
  $('phrase').textContent=state.phWord;$('translation').textContent='';
  $('pron-result').style.display='none';
  $('panel-lectura')?.scrollIntoView({behavior:'smooth',block:'center'});
  toast('Say it, then press record.');
});

/* --- llamada manos libres (detecta cuándo hablas y cuándo haces pausa) --- */
const vad={on:false,stream:null,ctx:null,an:null,raf:0,buf:null,floor:0.01,calib:[],voice:0,last:0,started:0,rec:false,starting:false,cool:0,wasBusy:false};
function setHF(on){const b=$('call-handsfree');if(!b)return;b.setAttribute('aria-pressed',on?'true':'false');b.textContent=on?'Hands-free: On':'Hands-free: Off';b.classList.toggle('primary',on);$('call-status').textContent=on?'Listening… speak and pause when you are done.':'Mantén presionado el botón para hablar'}
async function vadStart(){
  if(vad.on)return;
  if(!navigator.mediaDevices?.getUserMedia)return toast('Your browser does not support microphone recording.');
  try{vad.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){return toast('Microphone error: '+e.message)}
  const AC=window.AudioContext||window.webkitAudioContext;
  vad.ctx=new AC();vad.an=vad.ctx.createAnalyser();vad.an.fftSize=1024;
  vad.ctx.createMediaStreamSource(vad.stream).connect(vad.an);vad.buf=new Float32Array(vad.an.fftSize);
  vad.on=true;vad.calib=[];vad.voice=0;vad.rec=false;vad.starting=false;vad.cool=performance.now()+600;
  setHF(true);vadLoop();
}
function vadStop(){
  if(!vad.on)return;
  vad.on=false;cancelAnimationFrame(vad.raf);
  try{vad.stream&&vad.stream.getTracks().forEach(t=>t.stop())}catch(e){}
  try{vad.ctx&&vad.ctx.close()}catch(e){}
  vad.stream=null;vad.ctx=null;setHF(false);
}
function vadLoop(){
  if(!vad.on)return;
  vad.raf=requestAnimationFrame(vadLoop);
  vad.an.getFloatTimeDomainData(vad.buf);
  let sum=0;for(let i=0;i<vad.buf.length;i++)sum+=vad.buf[i]*vad.buf[i];
  const rms=Math.sqrt(sum/vad.buf.length),now=performance.now();
  if(state.callBusy){vad.voice=0;vad.wasBusy=true;return}
  if(vad.wasBusy){vad.wasBusy=false;vad.cool=now+900;$('call-status').textContent='Listening… speak and pause when you are done.'}
  if(vad.calib.length<40){vad.calib.push(rms);if(vad.calib.length===40)vad.floor=vad.calib.reduce((a,b)=>a+b,0)/40;return}
  const thr=Math.max(vad.floor*3,0.025),talking=$('call-talk-btn').classList.contains('recording');
  if(rms>thr){
    vad.voice++;vad.last=now;
    if(!talking&&!vad.rec&&!vad.starting&&now>vad.cool&&vad.voice>=8){
      vad.rec=true;vad.starting=true;vad.started=now;
      callStartTalk().then(()=>{$('call-status').textContent='Listening… speak and pause when you are done.'}).finally(()=>{vad.starting=false});
    }
  }else if(talking){
    if(vad.rec&&now-vad.last>1400&&now-vad.started>900){vad.rec=false;vad.voice=0;vad.cool=now+1200;callStopTalk()}
  }else if(!vad.starting){vad.voice=0;vad.rec=false}
}
$('call-handsfree')?.addEventListener('click',()=>vad.on?vadStop():vadStart());

/* --- prueba de nivel en el onboarding --- */
const LEVEL_QS=[
 {q:'She ___ a student.',o:['is','are','am'],a:0},
 {q:'I ___ coffee every morning.',o:['drink','drinks','drinking'],a:0},
 {q:'Yesterday we ___ to the market.',o:['go','went','gone'],a:1},
 {q:"There isn't ___ milk left.",o:['any','some','a'],a:0},
 {q:'If I ___ more time, I would travel more.',o:['have','had','will have'],a:1},
 {q:'She has lived here ___ 2019.',o:['for','since','from'],a:1},
 {q:'By the time we arrived, the movie ___.',o:['already started','has already started','had already started'],a:2},
 {q:'I wish I ___ that job offer last year.',o:['accepted','had accepted','would accept'],a:1}
];
let lvIdx=0,lvScore=0;
function lvShow(){
  const it=LEVEL_QS[lvIdx];
  $('ob-test-count').textContent='Question '+(lvIdx+1)+' of '+LEVEL_QS.length;
  $('ob-test-fill').style.width=Math.round(lvIdx/LEVEL_QS.length*100)+'%';
  $('ob-test-q').textContent=it.q;
  const opts=it.o.map((t,i)=>({t,i})).sort(()=>Math.random()-.5);
  $('ob-test-options').innerHTML=opts.map(x=>'<button type="button" class="ob-option" data-i="'+x.i+'" data-i18n-skip>'+esc(x.t)+'</button>').join('');
}
function lvFinish(){
  const lvl=lvScore<=2?'beginner':lvScore<=4?'elementary':lvScore<=6?'intermediate':'advanced';
  const name={beginner:'Beginner',elementary:'Elementary',intermediate:'Intermediate',advanced:'Advanced'}[lvl];
  obAnswers.cefr_level=lvl;
  $('ob-result-title').textContent='Your level: '+name;
  $('ob-result-text').textContent='You got '+lvScore+' of '+LEVEL_QS.length+' right. You can keep practicing and we adjust as you go.';
  showObStep(5);
}
$('ob-start-test')?.addEventListener('click',()=>{lvIdx=0;lvScore=0;showObStep(4);lvShow()});
$('ob-test-options')?.addEventListener('click',e=>{
  const b=e.target.closest('.ob-option');if(!b)return;
  if(Number(b.dataset.i)===LEVEL_QS[lvIdx].a)lvScore++;
  lvIdx++;if(lvIdx>=LEVEL_QS.length)lvFinish();else lvShow();
});
$('ob-result-continue')?.addEventListener('click',()=>finishOnboarding());

Object.assign(window,{cambiarPestana:(n,b)=>section(n,b),cambiarModoPronunciacion:pronMode,obtenerNuevaFrase:newPhrase,obtenerNuevoTemaHablaLibre:newTopic,obtenerNuevoTrabalenguas:newTwister,alternarGrabacion:toggleRecording,evaluarEscritura:analyzeWriting,cargarLectura:loadReading,evaluarLectura:evaluateReading,cargarDictado:loadDictation,evaluarDictado:evaluateDictation,cargarHistorial:loadProgress,procesarAuth:authSubmit,abrirModalAuth:showAuth,cerrarModalAuth:closeAuth,cerrarSesion:signOut,hablarNativo:t=>speak(t),hablarTrabalenguasNativo:t=>speak(t,.85)});
document.addEventListener('DOMContentLoaded',async()=>{bind();try{const s=await getSession();if(!recoveryMode)await syncUser(s?.user||null)}catch(e){console.error('[INIT]',e);if(!recoveryMode)syncUser(null)}});
Object.assign(window,{openLearningUnit,backToLPUnits,openLearningTopic,startLearningPractice,toggleLPRecording,submitLPWriting,submitLPReading,submitLPDictation,playGuideAudio,speak});
})();